### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by chatelao** [Laserlicht/MaerklinMotorola#11]
Thank you so much, your code is running on my Arduino Shield like a charm <3

![image](https://github.com/Laserlicht/MaerklinMotorola/assets/2461532/81b91e61-0c3f-4ab6-90de-657c7864f5ac)

<img width="566" alt="image" src="https://github.com/Laserlicht/MaerklinMotorola/assets/2461532/fcaee029-e09c-49b9-b2b5-7f564168c8a2">

**Comment by Laserlicht** [comment]
Thank you very much! I'm very pleased to hear that. :)

Have fun with it! What are you using the library for?

**Comment by Erwin007** [comment]
Ik heb de library van laserlicht verbeterd, want er zaten fouten in
waardoor de functies F1 .. F4 bij bepaalde snelheden niet werkten.



Op vr 5 jan 2024 om 22:05 schreef Laserlicht ***@***.***>:
