### ISSUE TITLE
MM2 support

### ISSUE THREAD

**Issue by leif-se** [Laserlicht/MaerklinMotorola#2]
I have written MM2 support to this. Tested with a CS3. 
I was not able to create a pull request.
[mm2.zip](https://github.com/Laserlicht/MaerklinMotorola/files/4014181/mm2.zip)

**Comment by probonopd** [comment]
Hi @leif-se that's great work. Unfortunately I don't have the hardware to test this on, but if you like I can create a pull request for you. Keep it up!

**Comment by Laserlicht** [comment]
https://github.com/Laserlicht/MaerklinMotorola/pull/3 added MM2 support
