### ISSUE TITLE
Schematic Questions

### ISSUE THREAD

**Issue by Thewbi** [Laserlicht/MaerklinMotorola#6]
Hello,

first, thank you for adding this project to github!

I want to use the project and currently I fail to understand the schematic. I am a beginner, so I guess I just do not have enought knowledge about circuits to understand what is going on.

My question is: Why is the output pin 6 of the optocoupler not connected to anything on the Microcontroller?
I can see that pin 7 VE (Enable Input Voltage) is connected to the microcontroller, I guess to enable or disable the reading of data. But why does the Microcontroller not read voltage from pin 6 of the optocoupler!

Thanks for your help.

Best Regards
Wolfgang

**Comment by Laserlicht** [comment]
Hi Wolfgang,

sorry - it's an mistake.

If you look into the old version, the pins are correct: https://github.com/Laserlicht/MaerklinMotorola/blob/18bdc5245c23ccefc5407ba3c8296c73676d3292/README.md

I will correct this mistake later!

Best Regards
Laserlicht

**Comment by Thewbi** [comment]
Thank you very much for the update!

**Comment by Laserlicht** [comment]
I leave it open until I corrected this issue ;)

**Comment by Laserlicht** [comment]
fixed with 1e50f9af661386868b2ad084ea1934192bd0f85f
